spring.data.mongodb.uri=mongodb+srv://ruturajsapare20_db_user:456mzx7Zu3@cluster0.ehyga86.mongodb.net/cloudshare?retryWrites=true&w=majority
server.servlet.context-path=/api/v1.0

spring.data.mongodb.auto-index-creation=true

server.port=${PORT:8080}
server.address=0.0.0.0

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

#Clerk Configuration
clerk.issuer=https://talented-flea-66.clerk.accounts.dev
clerk.jwks-uri=https://talented-flea-66.clerk.accounts.dev/.well-known/jwks.json
clerk.webhook.secret=whsec_NCuEZqkSeszn6qKVbwiUDvgRFJUvAzvz

#razorpay configuration
razorpay.key.id=rzp_test_SaF7kIaetcZGo1
razorpay.key.secret=1KOxCmfc7ijKhrwJD0XtUCF4

#Email configuration removed

# File upload configuration
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB